export default [
	{ name: "Afghanistan", flag: "\u{1F1E6}\u{1F1EB}", code: "AF", dial_code: "+93" },
	{ name: "\xC5land Islands", flag: "\u{1F1E6}\u{1F1FD}", code: "AX", dial_code: "+358" },
	{ name: "Albania", flag: "\u{1F1E6}\u{1F1F1}", code: "AL", dial_code: "+355" },
	{ name: "Algeria", flag: "\u{1F1E9}\u{1F1FF}", code: "DZ", dial_code: "+213" },
	{ name: "American Samoa", flag: "\u{1F1E6}\u{1F1F8}", code: "AS", dial_code: "+1684" },
	{ name: "Andorra", flag: "\u{1F1E6}\u{1F1E9}", code: "AD", dial_code: "+376" },
	{ name: "Angola", flag: "\u{1F1E6}\u{1F1F4}", code: "AO", dial_code: "+244" },
	{ name: "Anguilla", flag: "\u{1F1E6}\u{1F1EE}", code: "AI", dial_code: "+1264" },
	{ name: "Antarctica", flag: "\u{1F1E6}\u{1F1F6}", code: "AQ", dial_code: "+672" },
	{ name: "Antigua and Barbuda", flag: "\u{1F1E6}\u{1F1EC}", code: "AG", dial_code: "+1268" },
	{ name: "Argentina", flag: "\u{1F1E6}\u{1F1F7}", code: "AR", dial_code: "+54" },
	{ name: "Armenia", flag: "\u{1F1E6}\u{1F1F2}", code: "AM", dial_code: "+374" },
	{ name: "Aruba", flag: "\u{1F1E6}\u{1F1FC}", code: "AW", dial_code: "+297" },
	{ name: "Australia", flag: "\u{1F1E6}\u{1F1FA}", code: "AU", dial_code: "+61" },
	{ name: "Austria", flag: "\u{1F1E6}\u{1F1F9}", code: "AT", dial_code: "+43" },
	{ name: "Azerbaijan", flag: "\u{1F1E6}\u{1F1FF}", code: "AZ", dial_code: "+994" },
	{ name: "Bahamas", flag: "\u{1F1E7}\u{1F1F8}", code: "BS", dial_code: "+1242" },
	{ name: "Bahrain", flag: "\u{1F1E7}\u{1F1ED}", code: "BH", dial_code: "+973" },
	{ name: "Bangladesh", flag: "\u{1F1E7}\u{1F1E9}", code: "BD", dial_code: "+880" },
	{ name: "Barbados", flag: "\u{1F1E7}\u{1F1E7}", code: "BB", dial_code: "+1246" },
	{ name: "Belarus", flag: "\u{1F1E7}\u{1F1FE}", code: "BY", dial_code: "+375" },
	{ name: "Belgium", flag: "\u{1F1E7}\u{1F1EA}", code: "BE", dial_code: "+32" },
	{ name: "Belize", flag: "\u{1F1E7}\u{1F1FF}", code: "BZ", dial_code: "+501" },
	{ name: "Benin", flag: "\u{1F1E7}\u{1F1EF}", code: "BJ", dial_code: "+229" },
	{ name: "Bermuda", flag: "\u{1F1E7}\u{1F1F2}", code: "BM", dial_code: "+1441" },
	{ name: "Bhutan", flag: "\u{1F1E7}\u{1F1F9}", code: "BT", dial_code: "+975" },
	{
		name: "Bolivia, Plurinational State of bolivia",
		flag: "\u{1F1E7}\u{1F1F4}",
		code: "BO",
		dial_code: "+591",
	},
	{ name: "Bosnia and Herzegovina", flag: "\u{1F1E7}\u{1F1E6}", code: "BA", dial_code: "+387" },
	{ name: "Botswana", flag: "\u{1F1E7}\u{1F1FC}", code: "BW", dial_code: "+267" },
	{ name: "Bouvet Island", flag: "\u{1F1E7}\u{1F1FB}", code: "BV", dial_code: "+47" },
	{ name: "Brazil", flag: "\u{1F1E7}\u{1F1F7}", code: "BR", dial_code: "+55" },
	{
		name: "British Indian Ocean Territory",
		flag: "\u{1F1EE}\u{1F1F4}",
		code: "IO",
		dial_code: "+246",
	},
	{ name: "Brunei Darussalam", flag: "\u{1F1E7}\u{1F1F3}", code: "BN", dial_code: "+673" },
	{ name: "Bulgaria", flag: "\u{1F1E7}\u{1F1EC}", code: "BG", dial_code: "+359" },
	{ name: "Burkina Faso", flag: "\u{1F1E7}\u{1F1EB}", code: "BF", dial_code: "+226" },
	{ name: "Burundi", flag: "\u{1F1E7}\u{1F1EE}", code: "BI", dial_code: "+257" },
	{ name: "Cambodia", flag: "\u{1F1F0}\u{1F1ED}", code: "KH", dial_code: "+855" },
	{ name: "Cameroon", flag: "\u{1F1E8}\u{1F1F2}", code: "CM", dial_code: "+237" },
	{ name: "Canada", flag: "\u{1F1E8}\u{1F1E6}", code: "CA", dial_code: "+1" },
	{ name: "Cape Verde", flag: "\u{1F1E8}\u{1F1FB}", code: "CV", dial_code: "+238" },
	{ name: "Cayman Islands", flag: "\u{1F1F0}\u{1F1FE}", code: "KY", dial_code: "+345" },
	{ name: "Central African Republic", flag: "\u{1F1E8}\u{1F1EB}", code: "CF", dial_code: "+236" },
	{ name: "Chad", flag: "\u{1F1F9}\u{1F1E9}", code: "TD", dial_code: "+235" },
	{ name: "Chile", flag: "\u{1F1E8}\u{1F1F1}", code: "CL", dial_code: "+56" },
	{ name: "China", flag: "\u{1F1E8}\u{1F1F3}", code: "CN", dial_code: "+86" },
	{ name: "Christmas Island", flag: "\u{1F1E8}\u{1F1FD}", code: "CX", dial_code: "+61" },
	{ name: "Cocos (Keeling) Islands", flag: "\u{1F1E8}\u{1F1E8}", code: "CC", dial_code: "+61" },
	{ name: "Colombia", flag: "\u{1F1E8}\u{1F1F4}", code: "CO", dial_code: "+57" },
	{ name: "Comoros", flag: "\u{1F1F0}\u{1F1F2}", code: "KM", dial_code: "+269" },
	{ name: "Congo", flag: "\u{1F1E8}\u{1F1EC}", code: "CG", dial_code: "+242" },
	{
		name: "Congo, The Democratic Republic of the Congo",
		flag: "\u{1F1E8}\u{1F1E9}",
		code: "CD",
		dial_code: "+243",
	},
	{ name: "Cook Islands", flag: "\u{1F1E8}\u{1F1F0}", code: "CK", dial_code: "+682" },
	{ name: "Costa Rica", flag: "\u{1F1E8}\u{1F1F7}", code: "CR", dial_code: "+506" },
	{ name: "Cote d'Ivoire", flag: "\u{1F1E8}\u{1F1EE}", code: "CI", dial_code: "+225" },
	{ name: "Croatia", flag: "\u{1F1ED}\u{1F1F7}", code: "HR", dial_code: "+385" },
	{ name: "Cuba", flag: "\u{1F1E8}\u{1F1FA}", code: "CU", dial_code: "+53" },
	{ name: "Cyprus", flag: "\u{1F1E8}\u{1F1FE}", code: "CY", dial_code: "+357" },
	{ name: "Czech Republic", flag: "\u{1F1E8}\u{1F1FF}", code: "CZ", dial_code: "+420" },
	{ name: "Denmark", flag: "\u{1F1E9}\u{1F1F0}", code: "DK", dial_code: "+45" },
	{ name: "Djibouti", flag: "\u{1F1E9}\u{1F1EF}", code: "DJ", dial_code: "+253" },
	{ name: "Dominica", flag: "\u{1F1E9}\u{1F1F2}", code: "DM", dial_code: "+1767" },
	{ name: "Dominican Republic", flag: "\u{1F1E9}\u{1F1F4}", code: "DO", dial_code: "+1849" },
	{ name: "Ecuador", flag: "\u{1F1EA}\u{1F1E8}", code: "EC", dial_code: "+593" },
	{ name: "Egypt", flag: "\u{1F1EA}\u{1F1EC}", code: "EG", dial_code: "+20" },
	{ name: "El Salvador", flag: "\u{1F1F8}\u{1F1FB}", code: "SV", dial_code: "+503" },
	{ name: "Equatorial Guinea", flag: "\u{1F1EC}\u{1F1F6}", code: "GQ", dial_code: "+240" },
	{ name: "Eritrea", flag: "\u{1F1EA}\u{1F1F7}", code: "ER", dial_code: "+291" },
	{ name: "Estonia", flag: "\u{1F1EA}\u{1F1EA}", code: "EE", dial_code: "+372" },
	{ name: "Ethiopia", flag: "\u{1F1EA}\u{1F1F9}", code: "ET", dial_code: "+251" },
	{
		name: "Falkland Islands (Malvinas)",
		flag: "\u{1F1EB}\u{1F1F0}",
		code: "FK",
		dial_code: "+500",
	},
	{ name: "Faroe Islands", flag: "\u{1F1EB}\u{1F1F4}", code: "FO", dial_code: "+298" },
	{ name: "Fiji", flag: "\u{1F1EB}\u{1F1EF}", code: "FJ", dial_code: "+679" },
	{ name: "Finland", flag: "\u{1F1EB}\u{1F1EE}", code: "FI", dial_code: "+358" },
	{ name: "France", flag: "\u{1F1EB}\u{1F1F7}", code: "FR", dial_code: "+33" },
	{ name: "French Guiana", flag: "\u{1F1EC}\u{1F1EB}", code: "GF", dial_code: "+594" },
	{ name: "French Polynesia", flag: "\u{1F1F5}\u{1F1EB}", code: "PF", dial_code: "+689" },
	{
		name: "French Southern Territories",
		flag: "\u{1F1F9}\u{1F1EB}",
		code: "TF",
		dial_code: "+262",
	},
	{ name: "Gabon", flag: "\u{1F1EC}\u{1F1E6}", code: "GA", dial_code: "+241" },
	{ name: "Gambia", flag: "\u{1F1EC}\u{1F1F2}", code: "GM", dial_code: "+220" },
	{ name: "Georgia", flag: "\u{1F1EC}\u{1F1EA}", code: "GE", dial_code: "+995" },
	{ name: "Germany", flag: "\u{1F1E9}\u{1F1EA}", code: "DE", dial_code: "+49" },
	{ name: "Ghana", flag: "\u{1F1EC}\u{1F1ED}", code: "GH", dial_code: "+233" },
	{ name: "Gibraltar", flag: "\u{1F1EC}\u{1F1EE}", code: "GI", dial_code: "+350" },
	{ name: "Greece", flag: "\u{1F1EC}\u{1F1F7}", code: "GR", dial_code: "+30" },
	{ name: "Greenland", flag: "\u{1F1EC}\u{1F1F1}", code: "GL", dial_code: "+299" },
	{ name: "Grenada", flag: "\u{1F1EC}\u{1F1E9}", code: "GD", dial_code: "+1473" },
	{ name: "Guadeloupe", flag: "\u{1F1EC}\u{1F1F5}", code: "GP", dial_code: "+590" },
	{ name: "Guam", flag: "\u{1F1EC}\u{1F1FA}", code: "GU", dial_code: "+1671" },
	{ name: "Guatemala", flag: "\u{1F1EC}\u{1F1F9}", code: "GT", dial_code: "+502" },
	{ name: "Guernsey", flag: "\u{1F1EC}\u{1F1EC}", code: "GG", dial_code: "+44" },
	{ name: "Guinea", flag: "\u{1F1EC}\u{1F1F3}", code: "GN", dial_code: "+224" },
	{ name: "Guinea-Bissau", flag: "\u{1F1EC}\u{1F1FC}", code: "GW", dial_code: "+245" },
	{ name: "Guyana", flag: "\u{1F1EC}\u{1F1FE}", code: "GY", dial_code: "+592" },
	{ name: "Haiti", flag: "\u{1F1ED}\u{1F1F9}", code: "HT", dial_code: "+509" },
	{
		name: "Heard Island and Mcdonald Islands",
		flag: "\u{1F1ED}\u{1F1F2}",
		code: "HM",
		dial_code: "+672",
	},
	{
		name: "Holy See (Vatican City State)",
		flag: "\u{1F1FB}\u{1F1E6}",
		code: "VA",
		dial_code: "+379",
	},
	{ name: "Honduras", flag: "\u{1F1ED}\u{1F1F3}", code: "HN", dial_code: "+504" },
	{ name: "Hong Kong", flag: "\u{1F1ED}\u{1F1F0}", code: "HK", dial_code: "+852" },
	{ name: "Hungary", flag: "\u{1F1ED}\u{1F1FA}", code: "HU", dial_code: "+36" },
	{ name: "Iceland", flag: "\u{1F1EE}\u{1F1F8}", code: "IS", dial_code: "+354" },
	{ name: "India", flag: "\u{1F1EE}\u{1F1F3}", code: "IN", dial_code: "+91" },
	{ name: "Indonesia", flag: "\u{1F1EE}\u{1F1E9}", code: "ID", dial_code: "+62" },
	{
		name: "Iran, Islamic Republic of Persian Gulf",
		flag: "\u{1F1EE}\u{1F1F7}",
		code: "IR",
		dial_code: "+98",
	},
	{ name: "Iraq", flag: "\u{1F1EE}\u{1F1F6}", code: "IQ", dial_code: "+964" },
	{ name: "Ireland", flag: "\u{1F1EE}\u{1F1EA}", code: "IE", dial_code: "+353" },
	{ name: "Isle of Man", flag: "\u{1F1EE}\u{1F1F2}", code: "IM", dial_code: "+44" },
	{ name: "Israel", flag: "\u{1F1EE}\u{1F1F1}", code: "IL", dial_code: "+972" },
	{ name: "Italy", flag: "\u{1F1EE}\u{1F1F9}", code: "IT", dial_code: "+39" },
	{ name: "Jamaica", flag: "\u{1F1EF}\u{1F1F2}", code: "JM", dial_code: "+1876" },
	{ name: "Japan", flag: "\u{1F1EF}\u{1F1F5}", code: "JP", dial_code: "+81" },
	{ name: "Jersey", flag: "\u{1F1EF}\u{1F1EA}", code: "JE", dial_code: "+44" },
	{ name: "Jordan", flag: "\u{1F1EF}\u{1F1F4}", code: "JO", dial_code: "+962" },
	{ name: "Kazakhstan", flag: "\u{1F1F0}\u{1F1FF}", code: "KZ", dial_code: "+7" },
	{ name: "Kenya", flag: "\u{1F1F0}\u{1F1EA}", code: "KE", dial_code: "+254" },
	{ name: "Kiribati", flag: "\u{1F1F0}\u{1F1EE}", code: "KI", dial_code: "+686" },
	{
		name: "Korea, Democratic People's Republic of Korea",
		flag: "\u{1F1F0}\u{1F1F5}",
		code: "KP",
		dial_code: "+850",
	},
	{
		name: "Korea, Republic of South Korea",
		flag: "\u{1F1F0}\u{1F1F7}",
		code: "KR",
		dial_code: "+82",
	},
	{ name: "Kosovo", flag: "\u{1F1FD}\u{1F1F0}", code: "XK", dial_code: "+383" },
	{ name: "Kuwait", flag: "\u{1F1F0}\u{1F1FC}", code: "KW", dial_code: "+965" },
	{ name: "Kyrgyzstan", flag: "\u{1F1F0}\u{1F1EC}", code: "KG", dial_code: "+996" },
	{ name: "Laos", flag: "\u{1F1F1}\u{1F1E6}", code: "LA", dial_code: "+856" },
	{ name: "Latvia", flag: "\u{1F1F1}\u{1F1FB}", code: "LV", dial_code: "+371" },
	{ name: "Lebanon", flag: "\u{1F1F1}\u{1F1E7}", code: "LB", dial_code: "+961" },
	{ name: "Lesotho", flag: "\u{1F1F1}\u{1F1F8}", code: "LS", dial_code: "+266" },
	{ name: "Liberia", flag: "\u{1F1F1}\u{1F1F7}", code: "LR", dial_code: "+231" },
	{ name: "Libyan Arab Jamahiriya", flag: "\u{1F1F1}\u{1F1FE}", code: "LY", dial_code: "+218" },
	{ name: "Liechtenstein", flag: "\u{1F1F1}\u{1F1EE}", code: "LI", dial_code: "+423" },
	{ name: "Lithuania", flag: "\u{1F1F1}\u{1F1F9}", code: "LT", dial_code: "+370" },
	{ name: "Luxembourg", flag: "\u{1F1F1}\u{1F1FA}", code: "LU", dial_code: "+352" },
	{ name: "Macao", flag: "\u{1F1F2}\u{1F1F4}", code: "MO", dial_code: "+853" },
	{ name: "Macedonia", flag: "\u{1F1F2}\u{1F1F0}", code: "MK", dial_code: "+389" },
	{ name: "Madagascar", flag: "\u{1F1F2}\u{1F1EC}", code: "MG", dial_code: "+261" },
	{ name: "Malawi", flag: "\u{1F1F2}\u{1F1FC}", code: "MW", dial_code: "+265" },
	{ name: "Malaysia", flag: "\u{1F1F2}\u{1F1FE}", code: "MY", dial_code: "+60" },
	{ name: "Maldives", flag: "\u{1F1F2}\u{1F1FB}", code: "MV", dial_code: "+960" },
	{ name: "Mali", flag: "\u{1F1F2}\u{1F1F1}", code: "ML", dial_code: "+223" },
	{ name: "Malta", flag: "\u{1F1F2}\u{1F1F9}", code: "MT", dial_code: "+356" },
	{ name: "Marshall Islands", flag: "\u{1F1F2}\u{1F1ED}", code: "MH", dial_code: "+692" },
	{ name: "Martinique", flag: "\u{1F1F2}\u{1F1F6}", code: "MQ", dial_code: "+596" },
	{ name: "Mauritania", flag: "\u{1F1F2}\u{1F1F7}", code: "MR", dial_code: "+222" },
	{ name: "Mauritius", flag: "\u{1F1F2}\u{1F1FA}", code: "MU", dial_code: "+230" },
	{ name: "Mayotte", flag: "\u{1F1FE}\u{1F1F9}", code: "YT", dial_code: "+262" },
	{ name: "Mexico", flag: "\u{1F1F2}\u{1F1FD}", code: "MX", dial_code: "+52" },
	{
		name: "Micronesia, Federated States of Micronesia",
		flag: "\u{1F1EB}\u{1F1F2}",
		code: "FM",
		dial_code: "+691",
	},
	{ name: "Moldova", flag: "\u{1F1F2}\u{1F1E9}", code: "MD", dial_code: "+373" },
	{ name: "Monaco", flag: "\u{1F1F2}\u{1F1E8}", code: "MC", dial_code: "+377" },
	{ name: "Mongolia", flag: "\u{1F1F2}\u{1F1F3}", code: "MN", dial_code: "+976" },
	{ name: "Montenegro", flag: "\u{1F1F2}\u{1F1EA}", code: "ME", dial_code: "+382" },
	{ name: "Montserrat", flag: "\u{1F1F2}\u{1F1F8}", code: "MS", dial_code: "+1664" },
	{ name: "Morocco", flag: "\u{1F1F2}\u{1F1E6}", code: "MA", dial_code: "+212" },
	{ name: "Mozambique", flag: "\u{1F1F2}\u{1F1FF}", code: "MZ", dial_code: "+258" },
	{ name: "Myanmar", flag: "\u{1F1F2}\u{1F1F2}", code: "MM", dial_code: "+95" },
	{ name: "Namibia", flag: "\u{1F1F3}\u{1F1E6}", code: "NA", dial_code: "+264" },
	{ name: "Nauru", flag: "\u{1F1F3}\u{1F1F7}", code: "NR", dial_code: "+674" },
	{ name: "Nepal", flag: "\u{1F1F3}\u{1F1F5}", code: "NP", dial_code: "+977" },
	{ name: "Netherlands", flag: "\u{1F1F3}\u{1F1F1}", code: "NL", dial_code: "+31" },
	{ name: "Netherlands Antilles", flag: "", code: "AN", dial_code: "+599" },
	{ name: "New Caledonia", flag: "\u{1F1F3}\u{1F1E8}", code: "NC", dial_code: "+687" },
	{ name: "New Zealand", flag: "\u{1F1F3}\u{1F1FF}", code: "NZ", dial_code: "+64" },
	{ name: "Nicaragua", flag: "\u{1F1F3}\u{1F1EE}", code: "NI", dial_code: "+505" },
	{ name: "Niger", flag: "\u{1F1F3}\u{1F1EA}", code: "NE", dial_code: "+227" },
	{ name: "Nigeria", flag: "\u{1F1F3}\u{1F1EC}", code: "NG", dial_code: "+234" },
	{ name: "Niue", flag: "\u{1F1F3}\u{1F1FA}", code: "NU", dial_code: "+683" },
	{ name: "Norfolk Island", flag: "\u{1F1F3}\u{1F1EB}", code: "NF", dial_code: "+672" },
	{ name: "Northern Mariana Islands", flag: "\u{1F1F2}\u{1F1F5}", code: "MP", dial_code: "+1670" },
	{ name: "Norway", flag: "\u{1F1F3}\u{1F1F4}", code: "NO", dial_code: "+47" },
	{ name: "Oman", flag: "\u{1F1F4}\u{1F1F2}", code: "OM", dial_code: "+968" },
	{ name: "Pakistan", flag: "\u{1F1F5}\u{1F1F0}", code: "PK", dial_code: "+92" },
	{ name: "Palau", flag: "\u{1F1F5}\u{1F1FC}", code: "PW", dial_code: "+680" },
	{
		name: "Palestinian Territory, Occupied",
		flag: "\u{1F1F5}\u{1F1F8}",
		code: "PS",
		dial_code: "+970",
	},
	{ name: "Panama", flag: "\u{1F1F5}\u{1F1E6}", code: "PA", dial_code: "+507" },
	{ name: "Papua New Guinea", flag: "\u{1F1F5}\u{1F1EC}", code: "PG", dial_code: "+675" },
	{ name: "Paraguay", flag: "\u{1F1F5}\u{1F1FE}", code: "PY", dial_code: "+595" },
	{ name: "Peru", flag: "\u{1F1F5}\u{1F1EA}", code: "PE", dial_code: "+51" },
	{ name: "Philippines", flag: "\u{1F1F5}\u{1F1ED}", code: "PH", dial_code: "+63" },
	{ name: "Pitcairn", flag: "\u{1F1F5}\u{1F1F3}", code: "PN", dial_code: "+64" },
	{ name: "Poland", flag: "\u{1F1F5}\u{1F1F1}", code: "PL", dial_code: "+48" },
	{ name: "Portugal", flag: "\u{1F1F5}\u{1F1F9}", code: "PT", dial_code: "+351" },
	{ name: "Puerto Rico", flag: "\u{1F1F5}\u{1F1F7}", code: "PR", dial_code: "+1939" },
	{ name: "Qatar", flag: "\u{1F1F6}\u{1F1E6}", code: "QA", dial_code: "+974" },
	{ name: "Romania", flag: "\u{1F1F7}\u{1F1F4}", code: "RO", dial_code: "+40" },
	{ name: "Russia", flag: "\u{1F1F7}\u{1F1FA}", code: "RU", dial_code: "+7" },
	{ name: "Rwanda", flag: "\u{1F1F7}\u{1F1FC}", code: "RW", dial_code: "+250" },
	{ name: "Reunion", flag: "\u{1F1F7}\u{1F1EA}", code: "RE", dial_code: "+262" },
	{ name: "Saint Barthelemy", flag: "\u{1F1E7}\u{1F1F1}", code: "BL", dial_code: "+590" },
	{
		name: "Saint Helena, Ascension and Tristan Da Cunha",
		flag: "\u{1F1F8}\u{1F1ED}",
		code: "SH",
		dial_code: "+290",
	},
	{ name: "Saint Kitts and Nevis", flag: "\u{1F1F0}\u{1F1F3}", code: "KN", dial_code: "+1869" },
	{ name: "Saint Lucia", flag: "\u{1F1F1}\u{1F1E8}", code: "LC", dial_code: "+1758" },
	{ name: "Saint Martin", flag: "\u{1F1F2}\u{1F1EB}", code: "MF", dial_code: "+590" },
	{ name: "Saint Pierre and Miquelon", flag: "\u{1F1F5}\u{1F1F2}", code: "PM", dial_code: "+508" },
	{
		name: "Saint Vincent and the Grenadines",
		flag: "\u{1F1FB}\u{1F1E8}",
		code: "VC",
		dial_code: "+1784",
	},
	{ name: "Samoa", flag: "\u{1F1FC}\u{1F1F8}", code: "WS", dial_code: "+685" },
	{ name: "San Marino", flag: "\u{1F1F8}\u{1F1F2}", code: "SM", dial_code: "+378" },
	{ name: "Sao Tome and Principe", flag: "\u{1F1F8}\u{1F1F9}", code: "ST", dial_code: "+239" },
	{ name: "Saudi Arabia", flag: "\u{1F1F8}\u{1F1E6}", code: "SA", dial_code: "+966" },
	{ name: "Senegal", flag: "\u{1F1F8}\u{1F1F3}", code: "SN", dial_code: "+221" },
	{ name: "Serbia", flag: "\u{1F1F7}\u{1F1F8}", code: "RS", dial_code: "+381" },
	{ name: "Seychelles", flag: "\u{1F1F8}\u{1F1E8}", code: "SC", dial_code: "+248" },
	{ name: "Sierra Leone", flag: "\u{1F1F8}\u{1F1F1}", code: "SL", dial_code: "+232" },
	{ name: "Singapore", flag: "\u{1F1F8}\u{1F1EC}", code: "SG", dial_code: "+65" },
	{ name: "Slovakia", flag: "\u{1F1F8}\u{1F1F0}", code: "SK", dial_code: "+421" },
	{ name: "Slovenia", flag: "\u{1F1F8}\u{1F1EE}", code: "SI", dial_code: "+386" },
	{ name: "Solomon Islands", flag: "\u{1F1F8}\u{1F1E7}", code: "SB", dial_code: "+677" },
	{ name: "Somalia", flag: "\u{1F1F8}\u{1F1F4}", code: "SO", dial_code: "+252" },
	{ name: "South Africa", flag: "\u{1F1FF}\u{1F1E6}", code: "ZA", dial_code: "+27" },
	{ name: "South Sudan", flag: "\u{1F1F8}\u{1F1F8}", code: "SS", dial_code: "+211" },
	{
		name: "South Georgia and the South Sandwich Islands",
		flag: "\u{1F1EC}\u{1F1F8}",
		code: "GS",
		dial_code: "+500",
	},
	{ name: "Spain", flag: "\u{1F1EA}\u{1F1F8}", code: "ES", dial_code: "+34" },
	{ name: "Sri Lanka", flag: "\u{1F1F1}\u{1F1F0}", code: "LK", dial_code: "+94" },
	{ name: "Sudan", flag: "\u{1F1F8}\u{1F1E9}", code: "SD", dial_code: "+249" },
	{ name: "Suriname", flag: "\u{1F1F8}\u{1F1F7}", code: "SR", dial_code: "+597" },
	{ name: "Svalbard and Jan Mayen", flag: "\u{1F1F8}\u{1F1EF}", code: "SJ", dial_code: "+47" },
	{ name: "Eswatini", flag: "\u{1F1F8}\u{1F1FF}", code: "SZ", dial_code: "+268" },
	{ name: "Sweden", flag: "\u{1F1F8}\u{1F1EA}", code: "SE", dial_code: "+46" },
	{ name: "Switzerland", flag: "\u{1F1E8}\u{1F1ED}", code: "CH", dial_code: "+41" },
	{ name: "Syrian Arab Republic", flag: "\u{1F1F8}\u{1F1FE}", code: "SY", dial_code: "+963" },
	{ name: "Taiwan", flag: "\u{1F1F9}\u{1F1FC}", code: "TW", dial_code: "+886" },
	{ name: "Tajikistan", flag: "\u{1F1F9}\u{1F1EF}", code: "TJ", dial_code: "+992" },
	{
		name: "Tanzania, United Republic of Tanzania",
		flag: "\u{1F1F9}\u{1F1FF}",
		code: "TZ",
		dial_code: "+255",
	},
	{ name: "Thailand", flag: "\u{1F1F9}\u{1F1ED}", code: "TH", dial_code: "+66" },
	{ name: "Timor-Leste", flag: "\u{1F1F9}\u{1F1F1}", code: "TL", dial_code: "+670" },
	{ name: "Togo", flag: "\u{1F1F9}\u{1F1EC}", code: "TG", dial_code: "+228" },
	{ name: "Tokelau", flag: "\u{1F1F9}\u{1F1F0}", code: "TK", dial_code: "+690" },
	{ name: "Tonga", flag: "\u{1F1F9}\u{1F1F4}", code: "TO", dial_code: "+676" },
	{ name: "Trinidad and Tobago", flag: "\u{1F1F9}\u{1F1F9}", code: "TT", dial_code: "+1868" },
	{ name: "Tunisia", flag: "\u{1F1F9}\u{1F1F3}", code: "TN", dial_code: "+216" },
	{ name: "Turkey", flag: "\u{1F1F9}\u{1F1F7}", code: "TR", dial_code: "+90" },
	{ name: "Turkmenistan", flag: "\u{1F1F9}\u{1F1F2}", code: "TM", dial_code: "+993" },
	{ name: "Turks and Caicos Islands", flag: "\u{1F1F9}\u{1F1E8}", code: "TC", dial_code: "+1649" },
	{ name: "Tuvalu", flag: "\u{1F1F9}\u{1F1FB}", code: "TV", dial_code: "+688" },
	{ name: "Uganda", flag: "\u{1F1FA}\u{1F1EC}", code: "UG", dial_code: "+256" },
	{ name: "Ukraine", flag: "\u{1F1FA}\u{1F1E6}", code: "UA", dial_code: "+380" },
	{ name: "United Arab Emirates", flag: "\u{1F1E6}\u{1F1EA}", code: "AE", dial_code: "+971" },
	{ name: "United Kingdom", flag: "\u{1F1EC}\u{1F1E7}", code: "GB", dial_code: "+44" },
	{ name: "United States", flag: "\u{1F1FA}\u{1F1F8}", code: "US", dial_code: "+1" },
	{ name: "Uruguay", flag: "\u{1F1FA}\u{1F1FE}", code: "UY", dial_code: "+598" },
	{ name: "Uzbekistan", flag: "\u{1F1FA}\u{1F1FF}", code: "UZ", dial_code: "+998" },
	{ name: "Vanuatu", flag: "\u{1F1FB}\u{1F1FA}", code: "VU", dial_code: "+678" },
	{
		name: "Venezuela, Bolivarian Republic of Venezuela",
		flag: "\u{1F1FB}\u{1F1EA}",
		code: "VE",
		dial_code: "+58",
	},
	{ name: "Vietnam", flag: "\u{1F1FB}\u{1F1F3}", code: "VN", dial_code: "+84" },
	{ name: "Virgin Islands, British", flag: "\u{1F1FB}\u{1F1EC}", code: "VG", dial_code: "+1284" },
	{ name: "Virgin Islands, U.S.", flag: "\u{1F1FB}\u{1F1EE}", code: "VI", dial_code: "+1340" },
	{ name: "Wallis and Futuna", flag: "\u{1F1FC}\u{1F1EB}", code: "WF", dial_code: "+681" },
	{ name: "Yemen", flag: "\u{1F1FE}\u{1F1EA}", code: "YE", dial_code: "+967" },
	{ name: "Zambia", flag: "\u{1F1FF}\u{1F1F2}", code: "ZM", dial_code: "+260" },
	{ name: "Zimbabwe", flag: "\u{1F1FF}\u{1F1FC}", code: "ZW", dial_code: "+263" },
];
